@startuml Program
skinparam style strictuml
skinparam monochrome true


interface ASTNode {
    getLine(): int
    getColumn(): int
}

class AbstractASTNode {
    AbstractASTNode(int line, int column)
    getLine(): int
    getColumn(): int
    line: int
    column: int
}

class Program {
    statements: List<Statement>
}

interface Definition {
    getType(): Type
}

class AbstractDefinition {
    AbstractDefinition(int line, int column)
}

class VariableDefinition
class FunctionDefinition
class Type

class FunctionType {
    returnType: Type
    parameters: List<VariableDefinition>
}

ASTNode <|.. AbstractASTNode

AbstractASTNode <|-- Program
AbstractASTNode <|-- AbstractDefinition

Definition <|.. AbstractDefinition

Program o-- "0..n" Definition

Definition <|.. VariableDefinition
AbstractDefinition <|-- FunctionDefinition
AbstractStatement <|-- VariableDefinition

Type <-- Definition

FunctionType <-- FunctionDefinition

VariableDefinition "1" o-- "1" Type

FunctionDefinition "0..n" o-- VariableDefinition

@enduml
